# Generated by Django 5.2 on 2025-04-27 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='userid',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
