# Generated by Django 4.2.26 on 2025-11-08 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_bot_api', '0002_delete_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('action_type', models.CharField(choices=[('question_answer', 'QUESTION_ANSWER'), ('summarizer', 'SUMMARIZER'), ('generate_questions', 'GENERATE_QUESTIONS')], help_text='Type of action', max_length=50)),
                ('document_url', models.URLField(help_text='Document URL', max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', help_text='Processing status', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional processing metadata', null=True)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'db_table': 'processing_logs',
                'indexes': [models.Index(fields=['action_type', 'status'], name='processing__action__67b2a2_idx'), models.Index(fields=['created_at'], name='processing__created_9b87c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('url', models.URLField(help_text='URL of the PDF document', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Document title', max_length=255, null=True)),
                ('file_hash', models.CharField(db_index=True, help_text='Hash of document URL', max_length=64)),
                ('total_pages', models.IntegerField(blank=True, help_text='Total number of pages', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'indexes': [models.Index(fields=['file_hash'], name='documents_file_ha_3bbf78_idx'), models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is active')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('document', models.ForeignKey(help_text='Related document', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chat_bot_api.document')),
                ('user', models.ForeignKey(blank=True, help_text='User (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('action_type', models.CharField(choices=[('question_answer', 'QUESTION_ANSWER'), ('summarizer', 'SUMMARIZER'), ('generate_questions', 'GENERATE_QUESTIONS')], help_text='Type of action performed', max_length=50)),
                ('user_type', models.CharField(choices=[('User', 'USER'), ('Chatbot', 'CHATBOT'), ('System', 'SYSTEM')], default='User', help_text='Type of user (User or Chatbot)', max_length=50)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (question, page range, etc.)', null=True)),
                ('session', models.ForeignKey(help_text='Related chat session', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat_bot_api.chatsession')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'indexes': [models.Index(fields=['session', 'created_at'], name='conversatio_session_f04a5d_idx'), models.Index(fields=['action_type'], name='conversatio_action__ad03ce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chat_sessio_session_a3bcba_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active', 'last_activity'], name='chat_sessio_is_acti_df7e11_idx'),
        ),
    ]
